### PR TITLE
Added --min-size

### PR DESCRIPTION
**Pull request by rkarlsba**
Added an option to inhibit generation of empty (or very small) snapshots.

### CODE REVIEW

**Comment by mailinglists35** [comment]
whoa, this seem very useful, thank you!

**Comment by rkarlsba** [comment]
Seems there's a bug in here somewhere - if mypool/vol exists and mypool/subds isn't updated, but mypool/subds/anothersubds is, that isn't seen - I haven't figured out how to fix it yet - suggestions welcome.

**Comment by mailinglists35** [comment]
a complicated solution could be to enumerate each dataset when dataset is `//` instead of running recursively with `zfs snapshot -r`, then check individually for each dataset if `written` property matches the `--min-size` requirement

**Comment by highvoltage** [comment]
Looks great! Have anyone tested it and confirms that it works? Otherwise I'll do so and merge soon.

**Comment by beren12** [comment]
Ever find a fix for the bug?

**Comment by mailinglists35** [comment]
@beren12 someone must patch the code to emulate the recursive mode, like I explained in comment https://github.com/zfsonlinux/zfs-auto-snapshot/pull/59#issuecomment-275629775

meanwhile the workaround is to handle yourself the enumeration of datasets then iterate a non-recursive call of zfs-auto-snapshot for each dataset

**Comment by rkarlsba** [comment]
As @beren12 said, no, I didn't manage to fix that

**Comment by mailinglists35** [comment]
this PR is better than nothing, please merge if possible

**Comment by mailinglists35** [comment]
found a small issue: the script fails if `--debug` is unset.
the path that leads to fail is this:

if `--debug` is set, then `opt_verbose` is set to `1`
later on, in the code to check for `opt_min_size`, a decision to print verbose log is made on assumption that `opt_verbose` is greater than `0`.
however, if `--debug` is not set, `opt_verbose` remains unset and when the code reaches the decision step, it aborts as it cannot compare "nothing" to numerical "zero":
````
/usr/sbin/zfs-auto-snapshot: 174: [: -gt: unexpected operator
````
my local workaround is to set `opt_verbose` to `0` at the beginning of the script and later on when checking if `--quiet` is given (as it is the case when run from cron)

**Comment by mailinglists35** [comment]
@rkarlsba I found a hack

the logic which decides to snapshot recursive or individual is in this loop

`for ii in $CANDIDATES`

scrolling down, you will see that unless some conditions are met, at the end of the loop the candidate is considered to be recursive, which triggers the issue you observed.

my modification is to alter the logic in `for jj in $NOAUTO` before `for jj in $TARGETS_RECURSIVE` after this comment `Check whether the candidate name is a prefix of any excluded dataset name.`, replacing this check `elif [ "$jjj" != "${jjj#$iii}" ]` with a check that returns always true `elif true`, thus resulting in all eligible candidates being treated as non-recursive.

this way the zero-written parent is skipped for snap but it's recursive children are evaluated correctly instead of being skipped due to recursive evaluation of it's parent.

it's ugly, but it works for me using my parameters.
not guaranteed to work with other parameters

verified with `--dry-run --debug --syslog --label=daily --keep=31 --fast --default-exclude --min-size=1 //`

**Comment by mailinglists35** [comment]
on a second thought, I think the correct place to make the modification is just at the end of the loop, replacing 

        TARGETS_RECURSIVE="${TARGETS_RECURSIVE:+$TARGETS_RECURSIVE      }$ii" # nb: \t

with

        TARGETS_REGULAR="${TARGETS_REGULAR:+$TARGETS_REGULAR    }$ii" # nb: \t

**Comment by rkarlsba** [comment]
could you create a pull request with these changes, please?

**Comment by mailinglists35** [comment]
I am quite dumb at that. I would have already submitted a PR instead of all that talk if I was a git master :D :P

**Comment by mailinglists35** [comment]
@rkarlsba okay, my first attempt 

https://github.com/rkarlsba/zfs-auto-snapshot/compare/patch-3...mailinglists35:patch-1#diff-e7f2480c37404caadf77e766166e1b3a

**Comment by mailinglists35** [comment]
uhm, is this the correct url?

https://github.com/rkarlsba/zfs-auto-snapshot/pull/1

**Comment by mailinglists35** [comment]
Just a small correction:

````
 --min-size     Skip creating snapshot if `written` property is less than
	                 min-size kbytes..
````

^ this should be simple quote, not backquote, or else the shell would try to exec it...
so ````'written'```` instead of \`written\`

**Pull request merged**
